INSERT INTO department (department_name)
VALUES ("Management"),
    ("Finance"),
    ("Marketing"),
    ("Purchasing"),
    ("Logistics"),
    ("Production"),
    ("Human Resources");

INSERT INTO roles (title, salary,department_id)
VALUES ("Forklift operator", 59000.99, 5),
       ("Sales person", 45000.00,3),
       ("Warehouse driver", 40000.00,5),
       ("Material purchasing", 60000.00,4),
       ("Shipping clerk", 55000.00,5),
       ("Warehouse manager", 75000.00, 1),
       ("Warehouse supervisor", 80000.00, 1),
       ("Accountant", 75000.00, 2),
       ("CNC Tech", 80000.00, 6);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ("Jenesis","Cervantes",7,NULL),
        ("Kamari","Mullen",7,NULL),
        ("Shay","Marks",7,NULL),
        ("Amos","Briggs",7,NULL),
        ("Alia","Barron",7,NULL),
        ("Dustin","Morton",7,NULL),
        ("Mallory","Rich",7,NULL),
        ("Miller","Duke",2,1),
        ("Melani","Goodman",2,1),
        ("Philip","Bradford",2,1),
        ("Rhea","Bradford",2,1),
        ("Ander","Bush",2,1),
        ("Everlee","Wilcox",2,1),
        ("Jerry","Andrade",3,2),
        ("Emmy","Gray",3,2),
        ("Nicholas","Bonilla",3,2),
        ("Romina","McGee",3,2),
        ("Conner","Robinson",3,2),
        ("Nora","Williams",3,2),
        ("Oliver","Juarez",3,2),
        ("Juliet","Warner",3,2),
        ("Jaxton","Novak",4,3),
        ("Kaiya","Thompson",4,3),
        ("Theodore","Andersen",4,3),
        ("Zoie","Moon",4,3),
        ("Nova","Brewer",4,3),
        ("Thea","Rubio",4,3),
        ("Titan","Cook",5,4),
        ("Aaliyah","Suarez",5,4),
        ("Soren","Gallagher",5,4),
        ("Elliott","Stone",5,4),
        ("Finn","McConnell",6,5),
        ("Denise","Elliott",6,5),
        ("Blake","Hawkins",6,5),
        ("Ariel","King",6,5),
        ("Julian","Garrett",1,6),
        ("Tessa","Ortega",1,6),
        ("Kobe","Carlson",1,6);
